server:
  host: 127.0.0.1
  port: 8888

mongo:
  host: 106.14.3.255
  port: 27018
  username: admin
  password: admin
  dbname: admin
  params: 
    - directConnection=true
    - serverSelectionTimeoutMS=2000
    - appName=mongosh+2.2.2

redis:
  host: 106.14.3.255
  port: 6380
  db: 0

email:
  type: "163"
  username: linghechen_game
  auth: NADYQIWTHQTFDAVY
